version: "3"

services:
  api:
    image: registry.digitalocean.com/marcotuliocnd/promosdajess_api:latest
    container_name: promosdajess_api
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "3333:3333"
